# Generated by Django 5.1.6 on 2025-03-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_user_idproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='police',
            name='phonenumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
